name: VillagerMinion
version: 1.0.0
main: com.yourplugin.villagerminion.VillagerMinionPlugin
api-version: 1.21
author: YourName
commands:
  minions:
    description: Open the Villager Minion GUI
    usage: /minions
    permission: villagerminions.use
permissions:
  villagerminions.use:
    description: Allows access to the Minion GUI
    default: op
