name: Build VillagerMinion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: VillagerMinion
          path: target/VillagerMinion-1.0.0.jar
